sudo: false

language: php

php:
    - '7.3'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer selfupdate

script:
    - ./vendor/bin/phpbench run benchmarks/CacheLibrary --group=phpredis_read --report=cache_library --iterations=10 --revs=10000
